### ISSUE TITLE
Error in Program

### ISSUE THREAD

**Issue by mimranh** [kamejosh/Acoustic-Echo-Canceller#1]
Array formation and parentheses-style indexing with objects
of class 'dsp.IIRFilter' is not allowed.  Use objects of
class 'dsp.IIRFilter' only as scalars or use a cell array.

Error in geigel_finished (line 24)
roomImpulseResponse = impulseResponseGenerator( ...

**Comment by kamejosh** [comment]
which version of matlab are you using? code runs fine with given audio examples in version R2016b (9.1.0)

**Comment by mimranh** [comment]
I am using R2016a

**Comment by kamejosh** [comment]
code will only support latest version of matlab.
